[build]
  base = "/"
  publish = "/dist"
  command = "yarn build"

[context.production.environment]
  NODE_ENV = "production"
  TEST_VAL = "production"
[context.deploy-preview.environment]
  NODE_ENV = "development"
  TEST_VAL = "deploy-preview"
[context.branch-deploy.environment]
  NODE_ENV = "development"
  TEST_VAL = "branch-deploy"
